apiVersion: v1
kind: Secret
metadata:
  name: api-config-secrets-database
stringData:
  DB_HOST: mysql.mysql.svc.cluster.local
  DB_USER: root
  DB_PASSWORD: root
  DB_DATABASE: zdv
---
apiVersion: v1
kind: Secret
metadata:
  name: api-config-secrets-redis
stringData:
  REDIS_HOST: redis.redis.svc.cluster.local
  REDIS_PASSWORD: secret
  REDIS_SENTINEL: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-config-secrets-session
stringData:
  SESSION_SECRET: supersecretkey
---
apiVersion: v1
kind: Secret
metadata:
  name: api-config-secrets-oauth
stringData:
  OAUTH_CLIENT_ID: zdv
  OAUTH_CLIENT_SECRET: zdv