basePath: /v1
definitions:
  dto.UserResponse:
    properties:
      certifications:
        $ref: '#/definitions/dto.UserResponseCertifications'
      cid:
        type: integer
      controller_type:
        type: string
      created_at:
        type: string
      discord_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      operating_initials:
        type: string
      rating:
        type: string
      removal_reason:
        type: string
      roles:
        items:
          type: string
        type: array
      status:
        type: string
      updated_at:
        type: string
    type: object
  dto.UserResponseCertifications:
    properties:
      approach:
        type: string
      delivery:
        type: string
      enroute:
        type: string
      ground:
        type: string
      local:
        type: string
    type: object
  response.R:
    properties:
      data: {}
      status:
        type: string
    type: object
  user.Flightsv1:
    properties:
      alt:
        type: integer
      arr:
        type: string
      callsign:
        type: string
      cid:
        type: integer
      dep:
        type: string
      facility:
        type: string
      hdg:
        type: integer
      lastSeen:
        type: string
      lat:
        type: number
      lon:
        type: number
      route:
        type: string
      spd:
        type: integer
      type:
        type: string
    type: object
host: network.denartcc.org
info:
  contact:
    email: wm@denartcc.org
    name: Daniel Hawton
  description: Session Cookie
  license:
    name: Apache
    url: https://github.com/kzdv/api2/blob/main/LICENSE
  title: KZDV API
  version: "1.0"
paths:
  /v1/overflight:
    get:
      parameters:
      - description: Facility, defaults to ZDV if no facility id provided
        in: path
        name: fac
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.Flightsv1'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get Overflights for Facility
      tags:
      - overflight
  /v1/overflight/:facility:
    get:
      parameters:
      - description: Facility, defaults to ZDV if no facility id provided
        in: path
        name: fac
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.Flightsv1'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get Overflights for Facility
      tags:
      - overflight
  /v1/user:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get User Information
      tags:
      - user
    patch:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserResponse'
      - description: CID
        in: path
        name: cid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.R'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Patch User Information
      tags:
      - user
  /v1/user/:cid:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get User Information
      tags:
      - user
  /v1/user/:cid/roles:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get User Information
      tags:
      - user
  /v1/user/:cid/roles/:role:
    delete:
      parameters:
      - description: Role
        in: path
        name: role
        required: true
        type: string
      - description: CID
        in: path
        name: cid
        required: true
        type: string
      responses:
        "204":
          description: ""
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Remove User Role
      tags:
      - user
    put:
      parameters:
      - description: Role
        in: path
        name: role
        required: true
        type: string
      - description: CID
        in: path
        name: cid
        required: true
        type: string
      responses:
        "204":
          description: ""
        "309":
          description: ""
          schema:
            $ref: '#/definitions/response.R'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Add User Role
      tags:
      - user
  /v1/user/{cid}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserResponse'
      - description: CID
        in: path
        name: cid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.R'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Patch User Information
      tags:
      - user
  /v1/user/login:
    get:
      parameters:
      - description: Redirect URL
        in: path
        name: redirect
        type: string
      responses:
        "307":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Login to account
      tags:
      - user
      - oauth
  /v1/user/login/callback:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.R'
        "307":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.R'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Login callback
      tags:
      - user
      - oauth
  /v1/user/roles:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.R'
      summary: Get User Information
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
