name: Test
on:
  push:
    branches:
      - 'dev'
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.0
    - name: Run tests
      run: make test
    - name: Test docs
      run: make docs
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.0
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: make build
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:${{ steps.vars.outputs.sha_short }} .
    - name: Push Image
      if: ${{ github.event_name == 'push' }}
      run: docker push ${{ secrets.DOCKER_USERNAME }}/api:${{ steps.vars.outputs.sha_short }}
  deploy-gitops:
    name: Update GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if : ${{ github.event_name == 'push' && contains(fromJson('["refs/heads/dev", "refs/heads/main"]'), github.ref) }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PIPELINE_PAT }}
        repository: 'kzdv/devops'
        path: gitops
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git config user.name "{{ secrets.GH_PIPELINE_USERNAME }}"
        git config user.email "wm@denartcc.org"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update dev overlay
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops/overlays/dev
        kustomize edit set image denartcc/api=denartcc/api:$HASH
    - name: Update prod overlay
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops/overlays/prod
        kustomize edit set image denartcc/api=denartcc/api:$HASH
    - name: Commit manifests
      run: |
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git add .
        git commit -m "Update manifests for api"
    - name: Push to gitops repo
      run: |
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git push origin master

