name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.12
    - name: Run tests
      run: make test
    - name: Test docs
      run: make docs